repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: "v2.29.1"
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.4.0"
    hooks:
      - id: django-upgrade
        args: [--target-version, "3.2"]

  #- repo: https://github.com/ambv/black
  #  rev: "22.1.0"
  #  hooks:
  #    - id: black
  #      files: ^www/
  #      args: [--target-version, "py310"]
  #      additional_dependencies: ['click==8.0.4']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.0.1"
    hooks:
      - id: trailing-whitespace
        exclude_types: [csv, svg, markdown]
      - id: end-of-file-fixer
        exclude_types: [csv, svg]
        exclude: >
          (?x)^(
              www/locale/
          )
      - id: check-ast
        files: ^www/
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
        exclude: env_vars/gcs-dev.json
      - id: mixed-line-ending
        args: ['--fix=lf']
        exclude_types: [csv, svg]
      - id: fix-encoding-pragma
        args: ['--remove']
      - id: double-quote-string-fixer

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-no-eval
      - id: python-use-type-annotations

  - repo: https://github.com/pycqa/flake8
    rev: "6.1.0"
    hooks:
      - id: flake8
        files: ^www/
