loadBalancerGlobalIPAddress: 34.83.154.182
loadBalancerGlobalIPName: test-gke-ingress-global-ipv4
loadBalancerRootDomain: a-mt.shop
loadBalancerManagedCerticateMap: test-gke-ingress-map-entry
databaseConnectionName: django-gke-420513:us-west1:django-postgres
image: us-west1-docker.pkg.dev/django-gke-420513/test-gke-repo/django:latest
