---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-user
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: cicd-token
  annotations:
    kubernetes.io/service-account.name: cicd-user
type: kubernetes.io/service-account-token
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd-role
  namespace: default
rules:
# Can read everything
- apiGroups:
  - ""
  - apps
  - extensions
  - gateway.networking.k8s.io
  resources:
  - pods
  - services
  - namespaces
  - deployments
  - replicasets
  - jobs
  - gateways
  - httproutes
  verbs:
  - get
  - watch
  - list
# Can patch deployments in the default namespace
- apiGroups:
  - ""
  - apps
  resources:
  - deployments
  verbs:
  - patch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: cicd-user
roleRef:
  kind: Role
  name: cicd-role
  apiGroup: rbac.authorization.k8s.io
