apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:

      #+-------------------------------------
      #| API
      #+-------------------------------------

      - name: api
        # Replace  with your project ID or use `make template`
        # image: us-west1-docker.pkg.dev/test-gke-419405/test-gke-repo/polls
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        args:
          - "gunicorn"
          - "--bind=:8080"
          - "--workers=3"
          - "--worker-class=sync"
          - "--log-level=info"
          - "--log-file=-"
          - "--forwarded-allow-ips=*"
          - "--pid=gunicorn.pid"
          - "--timeout=60"
          - "--max-requests=1000"
          - "wsgi:application"
        env:
          - name: ADDITIONAL_ALLOWED_HOSTS
            value: "*"

          - name: DATABASE_HOST
            value: "127.0.0.1"

          - name: DATABASE_PORT
            value: "5432"

          # [START cloudsql_secrets]
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: cloudsql
                key: DATABASE_NAME

          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: cloudsql
                key: DATABASE_USERNAME

          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cloudsql
                key: DATABASE_PASSWORD
          # [END cloudsql_secrets]

        ports:
        - containerPort: 8080
          protocol: TCP

      #+-------------------------------------
      #| Cloud SQL Proxy (tunnels the connection to the database)
      #+-------------------------------------

      # [START proxy_container]
      - image: gcr.io/cloudsql-docker/gce-proxy:1.16
        name: cloudsql-proxy
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                  "-instances={{ .Values.databaseConnectionName }}=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-oauth-credentials
            mountPath: /secrets/cloudsql
            readOnly: true

          - name: ssl-certs
            mountPath: /etc/ssl/certs

          - name: cloudsql
            mountPath: /cloudsql
      # [END proxy_container]

      # [START volumes]
      volumes:
        - name: cloudsql-oauth-credentials
          secret:
            secretName: cloudsql-oauth-credentials

        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs

        - name: cloudsql
          emptyDir: {}
      # [END volumes]
