# https://cloud.google.com/kubernetes-engine/docs/concepts/gateway-api
---
# Create a NodePort
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: webapp
---
# Create a gateway
# Different types of gateways: https://cloud.google.com/kubernetes-engine/docs/how-to/deploying-gateways
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gateway
  annotations:
    # SSL certificates previously created using a DNS challenge
    networking.gke.io/certmap: {{ .Values.loadBalancerManagedCerticateMap }}
spec:
  gatewayClassName: gke-l7-global-external-managed
  addresses:
  - type: NamedAddress
    value: {{ .Values.loadBalancerGlobalIPName }}
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
  - name: http
    protocol: HTTP
    port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: main-route
spec:
  parentRefs:
  - name: gateway
  rules:
  - matches:
    - path:
        value: /
    backendRefs:
    - name: webapp
      port: 8080
#  - matches:
#    - path:
#        value: /shop
#    backendRefs:
#    - name: store
#      port: 80
